CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(256),
    password VARCHAR(256),
    balance FLOAT DEFAULT 0,
    withdrawn FLOAT DEFAULT 0
);

CREATE TABLE orders (
    user_id INT,
    num BIGINT,
    status VARCHAR(256) DEFAULT 'NEW',
    accrual FLOAT DEFAULT 0,
    uploaded TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE withdrawals (
    user_id INT,
    num BIGINT,
    amount FLOAT,
    processed TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);